site_name: Documentation for Amesto Fortytwo
site_description: Documentation and user guides for Amesto Fortytwo
copyright: Made on the run 🏃
theme:
  name: material
  logo: assets/amesto-fortytwo-white.png
  favicon: assets/favicon-32x32.png
  # font: Abhaya Libre
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "black"
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "black"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  # icon:
  #   repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
repo_url: https://github.com/amestofortytwo/public-docs.byfortytwo.com
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - tags
  - search
  - material-plausible
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
extra:
  analytics:
    provider: plausible
    domain: docs.byfortytwo.com
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!

        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AmestoFortytwo
    - icon: fontawesome/brands/github
      link: https://github.com/amestofortytwo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/amesto-fortytwo
